implemented in-app update functionality
Ni3verma/Safe-Box pull request #105
Opened 2021-11-04 09:12 UTC by AdiAr11

Signed-off-by: AdiAr11 <aditya2000arora@gmail.com>

## Description
Added in-app update feature

## If there is any UI change, please add screenshots.
<img src="ADD_LINK_HERE" height="400px" width = "200px"/>

## If you had to add any new dependency, please mention it here.

## Impacted Issue number
Closes #85 

## Type of change
Enhancement

## Code quality checklist
Just put an x in the [] where applicable.
- [] I ran `gradlew lint` and found no new error related to my code in the report.
- [] I have verified my changes on an emulator/ real device.
- [] I have added proper comments where code is complex.

2021-11-04 09:48 UTC, Ni3verma commented on .idea/deploymentTargetDropDown.xml
> +    <runningDeviceTargetSelectedWithDropDown>
Please revert this file from commit as this will be different in each system

2021-11-04 09:49 UTC, Ni3verma commented on .idea/gradle.xml
> +        <option name="gradleJvm" value="11" />
same here, .idea/** files can be ignored from commit

2021-11-04 09:49 UTC, Ni3verma commented on .idea/misc.xml
> +  <component name="ProjectRootManager" version="2" languageLevel="JDK_11" project-jdk-name="1.8" project-jdk-type="JavaSDK">
this also

2021-11-04 09:49 UTC, Ni3verma commented on .idea/vcs.xml
> -  <component name="GithubSharedProjectSettings">
and this

2021-11-04 09:51 UTC, Ni3verma commented on app/src/main/java/com/andryoga/safebox/ui/view/MainActivity.kt
> +    private lateinit var appUpdateManager: AppUpdateManager
shift this line to line 48 to keep all lateinit var together, it's easy to read code this way

2021-11-04 09:53 UTC, Ni3verma requested changes
@AdiAr11 I have added some comments.. most of them are related to reverting some changes.
I will read the documentation and then review app update related code.
one more suggestion, please add Timber info logs wherever you think it will be useful.

2021-11-04 10:01 UTC, Ni3verma commented on app/src/main/java/com/andryoga/safebox/ui/view/MainActivity.kt
> +        setAction("Install"){
"Install" need to be taken from string resource, should not be hardcoded in code

2021-11-04 10:01 UTC, Ni3verma commented on app/src/main/java/com/andryoga/safebox/ui/view/MainActivity.kt
> +                Toast.makeText(this, "Update Failed", Toast.LENGTH_SHORT).show()
take from string res : "Update Failed"

2021-11-04 10:50 UTC, AdiAr11 commented
> @AdiAr11 I have added some comments.. most of them are related to reverting some changes. I will read the documentation and then review app update related code. one more suggestion, please add Timber info logs wherever you think it will be useful.

I will make the required changes. Also, I haven't actually used Timber logs before, I'm still learning Android Development, sorry. I will look it up. 
Thank you !!

2021-11-05 09:34 UTC, closed without merging

2021-11-05 11:47 UTC, Ni3verma commented on app/src/main/java/com/andryoga/safebox/ui/view/MainActivity.kt
> +    private fun appUpdate(){
move private function below
all override functions are together

2021-11-05 11:47 UTC, Ni3verma commented on app/src/main/java/com/andryoga/safebox/ui/view/MainActivity.kt
> +    private val listener = InstallStateUpdatedListener{ state ->
move this above where all private val are defined

2021-11-05 11:47 UTC, Ni3verma commented on app/src/main/java/com/andryoga/safebox/ui/view/MainActivity.kt
> +    private fun snackbarForCompleteUpdate(){
same for this

2021-11-05 11:49 UTC, Ni3verma requested changes
have added some comments for code placement.
also are you not running git hooks? step 7 in contibuting.md file?
your PR is failing with detekt,ktlint errors.

2021-11-05 12:47 UTC, AdiAr11 commented
> have added some comments for code placement. also are you not running git hooks? step 7 in contibuting.md file? your PR is failing with detekt,ktlint errors.

I'm sorry but there was no check box for git hooks. I'll check and make the required changes

2021-11-08 06:20 UTC, Ni3verma commented on app/src/main/res/values/strings.xml
> -    <string name="common_delete">Delete</string>
Issue with merging
you removed few string resources

2021-11-08 06:21 UTC, Ni3verma commented on app/src/main/res/values/strings.xml
> -    <!--    delete record dialog-->
these also should not be removed

2021-11-08 06:21 UTC, Ni3verma commented on app/src/main/res/values/strings.xml
> -    <string name="enter_password_manually">For security reason, Please manually enter password</string>
this as well

2021-11-08 06:23 UTC, Ni3verma requested changes
while merging strings.xml, you accidently removed incoming changes
you had to merge : basically incoming changes + your changes

2021-11-08 07:11 UTC, AdiAr11 commented
> while merging strings.xml, you accidently removed incoming changes you had to merge : basically incoming changes + your changes

oh, sorry..I'll correct this mistake

2021-11-08 16:03 UTC, Ni3verma approved these changes

2021-11-09 13:25 UTC, AdiAr11 commented
Please let me know if something else needs to be changed

2021-11-10 05:31 UTC, Ni3verma commented on app/src/main/java/com/andryoga/safebox/ui/view/MainActivity.kt
> +        Snackbar.make(findViewById(R.id.content), "App update has been downloaded", Snackbar.LENGTH_INDEFINITE)
take this also from string

2021-11-10 05:33 UTC, Ni3verma requested changes
one small string hardcode issue
and currently you are always showing update dialog whenever it is available... like we discussed, keep some buffer... maybe ask after every 2/5 days.

2021-11-10 06:05 UTC, AdiAr11 commented
could you walk me through a little on how to go about asking for updating after 2/5 days?